microservice-discovery-eureka:
  image: docker.registry:5000/microservice-discovery-eureka
  ports:
  - 8761:8761
  hostname: discovery

microservice-provider-user:
  image: docker.registry:5000/microservice-provider-user
  ports:
  - 8000:8000
  links:
  - microservice-discovery-eureka

microservice-consumer-movie-ribbon:
  image: docker.registry:5000/microservice-consumer-movie-ribbon
  ports:
  - 8010:8010
  links:
  - microservice-discovery-eureka
  hostname: ribbon
#microservice-consumer-movie-ribbon-with-hystrix:
#  image: docker.registry:5000/microservice-consumer-movie-ribbon-with-hystrix
#  ports:
#  - 8011:8011
#  links:
#  - microservice-discovery-eureka
#  hostname: ribbon
#microservice-hystrix-dashboard:
#  image: docker.registry:5000/microservice-hystrix-dashboard
#  ports:
#  - 8030:8030
#  links:
#  - microservice-discovery-eureka
#  - microservice-hystrix-turbine
#microservice-hystrix-turbine:
#  image: docker.registry:5000/microservice-hystrix-turbine
#  ports:
#  - 8031:8031
#  links:
#  - microservice-discovery-eureka
#  - microservice-consumer-movie-ribbon-with-hystrix
microservice-api-gateway:
  image: docker.registry:5000/microservice-api-gateway
  ports:
  - 8050:8050
  links:
  - microservice-discovery-eureka
  - microservice-provider-user
  - microservice-consumer-movie-ribbon